theme: jekyll-theme-hacker
title: GatasMalas
description: Just a blog
future: True
published: True
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
gems:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
